site: Kongulov
title: Kongulov.dev
description: Ramiz’s blog about development
lang: en-US
timezone: Asia/Baku
data-theme: dark # default theme "dark" | "light"

paginate: 1
paginate_path: "page/:num"

#pagination:
#  enabled: true
#  permalink: '/page/:num.html'
#  sort_field: 'date'
#  sort_reverse: true
#  per_page: 10
#  trail:
#    before: 4
#    after: 4

author:
  name: Ramiz Kongulov
  bio: Ramiz’s blog about development
  url: https://kongulov.dev
  avatar: /assets/images/me200x200.jpg
  username: kongulov # general username
  github: kongulov # github username
  twitter: # twitter username
  email: ramiz.kongulov@gmail.com # email adress

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "https://kongulov.dev" # Domain Name of host. [username].github.io for github pages
#permalink: pretty

# local
#url: "http://localhost:4000" #


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  implementation: sass-embedded
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


